pub const OLLAMA_DEFAULT_ADDRESS: &str = "127.0.0.1";
pub const OLLAMA_DEFAULT_PORT: u16 = 11434;

pub const LLAMA_SERVER_DEFAULT_ADDRESS: &str = "127.0.0.1";
pub const LLAMA_SERVER_DEFAULT_PORT: u16 = 8080;

pub const LMSTUDIO_DEFAULT_ADDRESS: &str = "127.0.0.1";
pub const LMSTUDIO_DEFAULT_PORT: u16 = 1234;

pub const VLLM_DEFAULT_ADDRESS: &str = "127.0.0.1";
pub const VLLM_DEFAULT_PORT: u16 = 8000;

pub const OLLANA_CLIENT_PROXY_DEFAULT_ADDRESS: &str = "127.0.0.1";
// TODO: must be set dynamically based on SD reply
pub const OLLANA_CLIENT_PROXY_DEFAULT_PORT: u16 = OLLAMA_DEFAULT_PORT;

pub const OLLANA_SERVER_PROXY_DEFAULT_ADDRESS: &str = "0.0.0.0";
pub const OLLANA_SERVER_PROXY_DEFAULT_PORT: u16 = 20110;

pub const OLLANA_SERVER_DEFAULT_DISCOVERY_PORT: u16 = 20111;
