pub const OLLAMA_DEFAULT_PORT: u16 = 11434;
pub const OLLAMA_DEFAULT_ADDRESS: &str = "127.0.0.1";

pub const OLLANA_CLIENT_PROXY_DEFAULT_ADDRESS: &str = OLLAMA_DEFAULT_ADDRESS;
pub const OLLANA_CLIENT_PROXY_DEFAULT_PORT: u16 = OLLAMA_DEFAULT_PORT;

pub const OLLANA_SERVER_PROXY_DEFAULT_ADDRESS: &str = "0.0.0.0";
pub const OLLANA_SERVER_PROXY_DEFAULT_PORT: u16 = 11435;

pub const OLLANA_SERVER_DEFAULT_DISCOVERY_PORT: u16 = 11436;
