name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: moonrepo/setup-rust@v1
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check

    - uses: moonrepo/setup-rust@v1
      with:
        bins: cargo-make
        components: clippy
    - name: Run Clippy
      run: cargo make lint

    - name: Build
      run: cargo build --verbose

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
